---
- hosts: default
  gather_facts: no
  vars:
    homebrew_taps:
      - c-bata/kube-prompt
      - homebrew/boneyard
      - homebrew/cask
      - homebrew/cask-versions
      - jenkins-x/jx
      - sanemat/font
    homebrew_packages:
      - { name: awscli }
      - { name: colordiff }
      - { name: coreutils }
      - { name: curl }
      - { name: direnv }
      - { name: docker-machine-driver-xhyve }
      - { name: dvm }
      - { name: fontforge }
      - { name: flyway }
      - { name: fzf }
      - { name: ghq }
      - { name: git }
      - { name: git-flow }
      - { name: go }
      - { name: hub }
      - { name: jenv }
      - { name: jq }
      - { name: jx }
      - { name: kafka }
      - { name: kubectl }
      - { name: kubectx }
      - { name: kubernetes-helm }
      - { name: kube-prompt }
      - { name: maven }
      - { name: peco }
      - { name: reattach-to-user-namespace }
      - { name: rbenv }
      - { name: redis }
      - { name: ricty }
      - { name: sbt }
      - { name: scala }
      - { name: tfenv }
      - { name: the_silver_searcher }
      - { name: tmux }
      - { name: tree }
      - { name: wget }
      - { name: zsh-completions }
      - { name: zsh }
    homebrew_cask_packages:
      - { name: alfred }
      - { name: atom }
      - { name: clipy }
      - { name: docker }
      - { name: emacs }
      - { name: firefox }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: iterm2 }
      - { name: java8 }
      - { name: minikube }
      - { name: slack }
      - { name: sourcetree }
      - { name: jetbrains-toolbox }
      - { name: xquartz }
  tasks:
    - name: add repository for homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_taps }}"

    - name: update homebrew
      homebrew:
        update_homebrew: yes

    - name: install brew package
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        install_options: "{{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}"
      with_items: "{{homebrew_packages}}"

    - name: install brew cask packages
      homebrew_cask:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        install_options: "appdir=/Applications"
      with_items: "{{ homebrew_cask_packages }}"

    - name: copy ricty font
      shell: "cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/"
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
